apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
data:
  CONNECTION_STRING: U2VydmVyPWRiXFxBR0VVUztEYXRhYmFzZT1Nb3ZpZUh1YjtVc2VyIElkPXNhO1Bhc3N3b3JkPWthcmxhNnlhZ3VzdGluMTtFbmNyeXB0PVRydWU7VHJ1c3RTZXJ2ZXJDZXJ0aWZpY2F0ZT1UcnVlDQo=
  JWT_KEY: OTg5Z205ZXJ0Zzk0NWdqLDA5cmZnajBlNWdqLDk0NWpnLDA5ZXJqZywwOXczNCxnNwowOXc0ajUsZzANCg==
  DATABASE_PASSWORD: a2FybGE2eWFndXN0aW4xDQo=
